# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bbb67582d6e1beb5d3a0050fd08f4c7b713a9b82f6a6040e2e2d7f0a43c24090e85ceb219551034fbca80f2aa07176fb42dee690bf3bc4ba1a3e79b424f3293

test:
  secret_key_base: 5efd587af6a38d94387e18ee4da79106985f602aa0a449ebb8291cd4fdd0c108a5afe907d97dd0445de76ac06a315403974f0f80d1057cbe22fab3a4312ffd8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
